version: '3.4'

services:
  db:
    image: microsoft/mssql-server-windows-developer:latest
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"



  qna.questions.api:
    container_name : questionsapi             
    build:
      context: .
      dockerfile: Services\QnA.Questions.Api\Dockerfile
    restart: on-failure
    depends_on:
        - db

   
  qna.answers.api:
    container_name: answersapi
    build:
      context: .
      dockerfile: Services\QnA.Answers.Api\Dockerfile
    restart: on-failure
    depends_on:
        - db

  qna.drafts.api:
    container_name: draftsapi
    build:
      context: .
      dockerfile: Services\QnA.Drafts.Api\Dockerfile
    restart: on-failure
    depends_on:
        - db

  qna.identity.api:
    container_name: identityapi
    build:
      context: .
      dockerfile: Services\QnA.Identity.Api\Dockerfile
    restart: on-failure
    depends_on:
        - db

