export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_UPDATED_PROFILE_IMG = "USER_UPDATED_PROFILE_IMG"
export const USER_QUESTIONS_LOADED = "USER_QUESTIONS_LOADED";
export const USER_QUESTIONS_LOADING = "USER_QUESTIONS_LOADING";
export const USER_STATS_UPDATING = "USER_STATS_UPDATING";
export const USER_STATS_UPADTED = "USER_STATS_UPDATED";
export const USER_LOADING_MY_QUESTIONS = "USER_LOADING_MY_QUESTIONS";
export const USER_MY_QUESTIONS_LOADED = "USER_MY_QUESTIONS_LOADED";
export const USER_UPDATE_QUESTIONS = "USER_UPDATE_QUESTIONS";
export const USER_RESET_PAGE="USER_RESET_PAGE";
export const USER_FOLLOW_QUESTION = 'USER_FOLLOW_QUESTIONS'
export const USER_UNFOLLOW_QUESTION = 'USER_UNFOLLOW_QUESTION'
export const USER_SAVED_QUESTION = 'USER_SAVED_QUESTION'
export const USER_UNSAVED_QUESTION = 'USER_UNSAVED_QUESTION'

