version: 0.0
os: windows
files:
  - source: .\server\Server\Api
    distination: C:\QnaServer
hooks:
  ApplicationStop:
    - location: .\RemoveApp.ps1
      timeout: 30
  ApplicationStart:
    - location: .\InstallApp.ps1
      timeout: 30
  ValidateService:
    - location: .\ValidateInstall.ps1
      timeout: 30