export const UPDATE_QUESTIONS = "USER_UPDATE_QUESTIONS";
export const RESET_PAGE="USER_RESET_PAGE";
export const IS_FEED_LOADING = "IS_FEED_LOADING";
export const POSTING_QUESTION_TO_FEED = "POSTING_QUESTION_TO_FEED";
export const QUESTION_POSTED_TO_FEED = "QUESTION_POSTED_TO_FEED";
export const LOAD_QUESTIONS_FIRST_TIME ="LOAD_QUESTIONS_FIRST_TIME";